In [1]:
import numpy as np

## Example 1.3

In [26]:
# Prior distribution
p_b = .6
p_m = .2
p_B = np.array([1-p_b, p_b])
p_M = np.array([1-p_m, p_m])

In [27]:
# Probability Knife muderer, given buttler, maid
p_k_given_bm = np.array([[.3, .2], [.6, .1]])
p_k_given_bm

array([[0.3, 0.2],
       [0.6, 0.1]])

In [28]:
# sum over m: p_k_given_bm * prior_m
A1 = np.dot(p_k_given_bm[1,:], p_M)
A1

0.5

In [29]:
# 
A2 = 0
for ib, pb in enumerate(p_B):
    A2 += pb * np.dot(p_k_given_bm[ib,:],p_M)
A2

0.41200000000000003

In [30]:
result = p_B[1] * A1/A2
result

0.7281553398058251

## Example 1.7

In [31]:
p_c_eq_1 = np.array([[.1, .99], [.8, .25]])
p_c_eq_1

array([[0.1 , 0.99],
       [0.8 , 0.25]])

In [34]:
p_c_eq_0 = 1-p_c_eq_1
p_c_eq_0

array([[0.9 , 0.01],
       [0.2 , 0.75]])

In [35]:
p_A = np.array([.35, .65])
p_B = np.array([.23, .77])
p_A, p_B

(array([0.35, 0.65]), array([0.23, 0.77]))

In [37]:
a1 = p_A[1]*np.dot(p_c_eq_0[1,:], p_B) 
a1

0.40527500000000005

In [40]:
a0 = p_A[0]*np.dot(p_c_eq_0[0,:], p_B) 
a0

0.075145

In [41]:
result = a1 / (a1+a0)
result

0.8435847799841805